### ISSUE TITLE
v1.1.0 breaks sudoers file on Ubuntu Focal (20.04)

### ISSUE THREAD

**Issue by mprasil** [andrewrothstein/ansible-sudoers#11]
`@includedir /etc/sudoers.d` is an invalid syntax in older Ubuntu distribution. (possibly others, haven't investigated this much) and leads to following error breaking sudo functionality:

```
>>> /etc/sudoers: syntax error near line 30 <<<
sudo: parse error in /etc/sudoers near line 30
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```

[This step](https://github.com/andrewrothstein/ansible-sudoers/blob/b8524d5c71e5cb36d3db7c6f27f1293987927806/tasks/main.yml#L47-L53) needs to be conditional either based on distribution or sudo version.

It might be a good idea to also extend CI workflow to run something simple like `sudo true` as a final check whether the configuration is correct when role is finished, it would likely catch this specific issue.

**Comment by andrewrothstein** [comment]
I added the config test u suggested. thanks. At the expense of always using the #includedir syntax even on newer version of sudo, it now continues to work for the older versions. pls try v1.2.0 that I just published to the galaxy.

**Comment by mprasil** [comment]
Yep, I can confirm, that `v1.2.0` fixes the issue. Thanks for quick response!
